### PR TITLE
[xOWL] Prepare repo for solidity 0.4 bridge contract

### PR DESCRIPTION
**Pull request by fleupold**
In order to properly bridge the OWL token to xDAI we need a custom implementation of the BridgedToken (based on [the default one](https://github.com/poanetwork/tokenbridge-contracts/blob/feb0ba555cb8bf74f7fa21911120d878715a0a84/contracts/PermittableToken.sol#L5). Our custom implementation will expose a burnOWL method that allows collecting OWL in a designated receiver account. This receiver account can send the collected OWL back to mainnet to properly burn them there.

The existing bridge contracts are written in solidity 0.4. and there is no plan to update them anytime soon. In order to coexist in this repo, I tried using [buidler](https://buidler.dev/getting-started/) which has a bunch of drawbacks when it comes to deploying tokens on-chain (networks are not written to artefacts).

Using different truffle config files, I was able to get a truffle project to work with different compiler versions. All v5 contracts go into a separate folder which is the compile target of the default config.

In the next step, I will add a `contracts/4` subfolder and the following config:

```js
const truffleConfig = require('./truffle.js')

module.exports = {
  ...truffleConfig,
  contracts_directory: './contracts/4/'
  compilers: {
    solc: {
      version: 0.4.24,
    }
  }
}

```

Then we can compile the other contracts using `yarn truffle compile --config truffle.4.js`

### Testplan

I tested that other than compilation, migration and unit tests work with artefacts of mixed solidity versions without issues.

### CODE REVIEW

**Comment by rmeissner** [comment]
The changes look straight forward, but I would love to know if there are other drawbacks besides the not writing out the network info. Also should we adjust our migration to capture the network info? The project already uses scripts to inject network info for the npm package, maybe this could be used somehow.

**Comment by fleupold** [comment]
> I would love to know if there are other drawbacks besides the not writing out the network info

I assume you are asking for drawback of using buidler over truffle. We would also have to rewrite our migration scripts in pretty fundamental ways (both for tests as well as for the migration). Moreover, artefacts are written in a different directory so all projects depending on OWL would have to change their imports. 

All of this is possible. However keeping the existing truffle project structure and just adding a separate compile step for v0.4 contracts (which is also the case for buidler) seems more pragmatic to me. 

Another alternative would be to have a separate repo for the BridgedOwl contract, but I'm not a fan of having too many repos.

**Comment by fleupold** [comment]
@rmeissner did my comment address your questions or do you have any other concerns?

**Comment by rmeissner** [comment]
@fleupold yes and I agree that this seems a sensible appeoach

**Review by rmeissner — APPROVED** [review]

**Review by josojo — APPROVED** [review]
It really sucks that they are not supporting newer solidity versions. But I can also understand their point of view. Audits are expensive.


I can not yet supervise how many changes this requires. I remember anxo really needed to maintain two different migration codebases for the dutchx: 
https://github.com/gnosis/dx-contracts/tree/master/src


Hopefully, we find a method to not maintain two migration scripts and just leverage truffle configurations.
I am approving, as I don't' know a better way to go forward and in general, this approach seems reasonable.

**Pull request merged**
